# https://developers.eventstore.com/server/v20.10/installation.html#use-docker-compose

version: "3.4"

services:
  mongo:
    image: candis/mongo-replica-set
    restart: always
    ports:
      - "27017:27017"
      - "27018:27018"
      - "27019:27019"
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

